export default [
  { digits_2: 11, digits_4: 1111, title: 'Oilseed and Grain Farming' },
  { digits_2: 11, digits_4: 1112, title: 'Vegetable and Melon Farming' },
  { digits_2: 11, digits_4: 1113, title: 'Fruit and Tree Nut Farming' },
  { digits_2: 11, digits_4: 1114, title: 'Greenhouse, Nursery, and Floriculture Production' },
  { digits_2: 11, digits_4: 1119, title: 'Other Crop Farming' },
  { digits_2: 11, digits_4: 1121, title: 'Cattle Ranching and Farming' },
  { digits_2: 11, digits_4: 1122, title: 'Hog and Pig Farming' },
  { digits_2: 11, digits_4: 1123, title: 'Poultry and Egg Production' },
  { digits_2: 11, digits_4: 1124, title: 'Sheep and Goat Farming' },
  { digits_2: 11, digits_4: 1125, title: 'Aquaculture' },
  { digits_2: 11, digits_4: 1129, title: 'Other Animal Production' },
  { digits_2: 11, digits_4: 1131, title: 'Timber Tract Operations' },
  { digits_2: 11, digits_4: 1132, title: 'Forest Nurseries and Gathering of Forest Products' },
  { digits_2: 11, digits_4: 1133, title: 'Logging' },
  { digits_2: 11, digits_4: 1141, title: 'Fishing' },
  { digits_2: 11, digits_4: 1142, title: 'Hunting and Trapping' },
  { digits_2: 11, digits_4: 1151, title: 'Support Activities for Crop Production' },
  { digits_2: 11, digits_4: 1152, title: 'Support Activities for Animal Production' },
  { digits_2: 11, digits_4: 1153, title: 'Support Activities for Forestry' },
  { digits_2: 21, digits_4: 2111, title: 'Oil and Gas Extraction' },
  { digits_2: 21, digits_4: 2121, title: 'Coal Mining' },
  { digits_2: 21, digits_4: 2122, title: 'Metal Ore Mining' },
  { digits_2: 21, digits_4: 2123, title: 'Nonmetallic Mineral Mining and Quarrying' },
  { digits_2: 21, digits_4: 2131, title: 'Support Activities for Mining' },
  { digits_2: 22, digits_4: 2211, title: 'Electric Power Generation, Transmission and Distribution' },
  { digits_2: 22, digits_4: 2212, title: 'Natural Gas Distribution ' },
  { digits_2: 22, digits_4: 2213, title: 'Water, Sewage and Other Systems ' },
  { digits_2: 23, digits_4: 2361, title: 'Residential Building Construction' },
  { digits_2: 23, digits_4: 2362, title: 'Nonresidential Building Construction' },
  { digits_2: 23, digits_4: 2371, title: 'Utility System Construction' },
  { digits_2: 23, digits_4: 2372, title: 'Land Subdivision' },
  { digits_2: 23, digits_4: 2373, title: 'Highway, Street, and Bridge Construction' },
  { digits_2: 23, digits_4: 2379, title: 'Other Heavy and Civil Engineering Construction' },
  { digits_2: 23, digits_4: 2381, title: 'Foundation, Structure, and Building Exterior Contractors' },
  { digits_2: 23, digits_4: 2382, title: 'Building Equipment Contractors' },
  { digits_2: 23, digits_4: 2383, title: 'Building Finishing Contractors' },
  { digits_2: 23, digits_4: 2389, title: 'Other Specialty Trade Contractors' },
  { digits_2: 31, digits_4: 3111, title: 'Animal Food Manufacturing' },
  { digits_2: 31, digits_4: 3112, title: 'Grain and Oilseed Milling' },
  { digits_2: 31, digits_4: 3113, title: 'Sugar and Confectionery Product Manufacturing' },
  { digits_2: 31, digits_4: 3114, title: 'Fruit and Vegetable Preserving and Specialty Food Manufacturing' },
  { digits_2: 31, digits_4: 3115, title: 'Dairy Product Manufacturing' },
  { digits_2: 31, digits_4: 3116, title: 'Animal Slaughtering and Processing' },
  { digits_2: 31, digits_4: 3117, title: 'Seafood Product Preparation and Packaging' },
  { digits_2: 31, digits_4: 3118, title: 'Bakeries and Tortilla Manufacturing' },
  { digits_2: 31, digits_4: 3119, title: 'Other Food Manufacturing' },
  { digits_2: 31, digits_4: 3121, title: 'Beverage Manufacturing' },
  { digits_2: 31, digits_4: 3122, title: 'Tobacco Manufacturing' },
  { digits_2: 31, digits_4: 3131, title: 'Fiber, Yarn, and Thread Mills' },
  { digits_2: 31, digits_4: 3132, title: 'Fabric Mills' },
  { digits_2: 31, digits_4: 3133, title: 'Textile and Fabric Finishing and Fabric Coating Mills' },
  { digits_2: 31, digits_4: 3141, title: 'Textile Furnishings Mills' },
  { digits_2: 31, digits_4: 3149, title: 'Other Textile Product Mills' },
  { digits_2: 31, digits_4: 3151, title: 'Apparel Knitting Mills' },
  { digits_2: 31, digits_4: 3152, title: 'Cut and Sew Apparel Manufacturing' },
  { digits_2: 31, digits_4: 3159, title: 'Apparel Accessories and Other Apparel Manufacturing' },
  { digits_2: 31, digits_4: 3161, title: 'Leather and Hide Tanning and Finishing' },
  { digits_2: 31, digits_4: 3162, title: 'Footwear Manufacturing' },
  { digits_2: 31, digits_4: 3169, title: 'Other Leather and Allied Product Manufacturing' },
  { digits_2: 32, digits_4: 3211, title: 'Sawmills and Wood Preservation' },
  { digits_2: 32, digits_4: 3212, title: 'Veneer, Plywood, and Engineered Wood Product Manufacturing' },
  { digits_2: 32, digits_4: 3219, title: 'Other Wood Product Manufacturing' },
  { digits_2: 32, digits_4: 3221, title: 'Pulp, Paper, and Paperboard Mills' },
  { digits_2: 32, digits_4: 3222, title: 'Converted Paper Product Manufacturing' },
  { digits_2: 32, digits_4: 3231, title: 'Printing and Related Support Activities' },
  { digits_2: 32, digits_4: 3241, title: 'Petroleum and Coal Products Manufacturing' },
  { digits_2: 32, digits_4: 3251, title: 'Basic Chemical Manufacturing' },
  {
    digits_2: 32,
    digits_4: 3252,
    title: 'Resin, Synthetic Rubber, and Artificial and Synthetic Fibers and Filaments Manufacturing'
  },
  { digits_2: 32, digits_4: 3253, title: 'Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing' },
  { digits_2: 32, digits_4: 3254, title: 'Pharmaceutical and Medicine Manufacturing' },
  { digits_2: 32, digits_4: 3255, title: 'Paint, Coating, and Adhesive Manufacturing' },
  { digits_2: 32, digits_4: 3256, title: 'Soap, Cleaning Compound, and Toilet Preparation Manufacturing' },
  { digits_2: 32, digits_4: 3259, title: 'Other Chemical Product and Preparation Manufacturing' },
  { digits_2: 32, digits_4: 3261, title: 'Plastics Product Manufacturing' },
  { digits_2: 32, digits_4: 3262, title: 'Rubber Product Manufacturing' },
  { digits_2: 32, digits_4: 3271, title: 'Clay Product and Refractory Manufacturing' },
  { digits_2: 32, digits_4: 3272, title: 'Glass and Glass Product Manufacturing' },
  { digits_2: 32, digits_4: 3273, title: 'Cement and Concrete Product Manufacturing' },
  { digits_2: 32, digits_4: 3274, title: 'Lime and Gypsum Product Manufacturing' },
  { digits_2: 32, digits_4: 3279, title: 'Other Nonmetallic Mineral Product Manufacturing' },
  { digits_2: 33, digits_4: 3311, title: 'Iron and Steel Mills and Ferroalloy Manufacturing' },
  { digits_2: 33, digits_4: 3312, title: 'Steel Product Manufacturing from Purchased Steel' },
  { digits_2: 33, digits_4: 3313, title: 'Alumina and Aluminum Production and Processing' },
  { digits_2: 33, digits_4: 3314, title: 'Nonferrous Metal (except Aluminum) Production and Processing' },
  { digits_2: 33, digits_4: 3315, title: 'Foundries' },
  { digits_2: 33, digits_4: 3321, title: 'Forging and Stamping' },
  { digits_2: 33, digits_4: 3322, title: 'Cutlery and Handtool Manufacturing' },
  { digits_2: 33, digits_4: 3323, title: 'Architectural and Structural Metals Manufacturing' },
  { digits_2: 33, digits_4: 3324, title: 'Boiler, Tank, and Shipping Container Manufacturing' },
  { digits_2: 33, digits_4: 3325, title: 'Hardware Manufacturing' },
  { digits_2: 33, digits_4: 3326, title: 'Spring and Wire Product Manufacturing' },
  { digits_2: 33, digits_4: 3327, title: 'Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing' },
  { digits_2: 33, digits_4: 3328, title: 'Coating, Engraving, Heat Treating, and Allied Activities' },
  { digits_2: 33, digits_4: 3329, title: 'Other Fabricated Metal Product Manufacturing' },
  { digits_2: 33, digits_4: 3331, title: 'Agriculture, Construction, and Mining Machinery Manufacturing' },
  { digits_2: 33, digits_4: 3332, title: 'Industrial Machinery Manufacturing' },
  { digits_2: 33, digits_4: 3333, title: 'Commercial and Service Industry Machinery Manufacturing' },
  {
    digits_2: 33,
    digits_4: 3334,
    title: 'Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing'
  },
  { digits_2: 33, digits_4: 3335, title: 'Metalworking Machinery Manufacturing' },
  { digits_2: 33, digits_4: 3336, title: 'Engine, Turbine, and Power Transmission Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3339, title: 'Other General Purpose Machinery Manufacturing' },
  { digits_2: 33, digits_4: 3341, title: 'Computer and Peripheral Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3342, title: 'Communications Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3343, title: 'Audio and Video Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3344, title: 'Semiconductor and Other Electronic Component Manufacturing' },
  {
    digits_2: 33,
    digits_4: 3345,
    title: 'Navigational, Measuring, Electromedical, and Control Instruments Manufacturing'
  },
  { digits_2: 33, digits_4: 3346, title: 'Manufacturing and Reproducing Magnetic and Optical Media' },
  { digits_2: 33, digits_4: 3351, title: 'Electric Lighting Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3352, title: 'Household Appliance Manufacturing' },
  { digits_2: 33, digits_4: 3353, title: 'Electrical Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3359, title: 'Other Electrical Equipment and Component Manufacturing' },
  { digits_2: 33, digits_4: 3361, title: 'Motor Vehicle Manufacturing' },
  { digits_2: 33, digits_4: 3362, title: 'Motor Vehicle Body and Trailer Manufacturing' },
  { digits_2: 33, digits_4: 3363, title: 'Motor Vehicle Parts Manufacturing' },
  { digits_2: 33, digits_4: 3364, title: 'Aerospace Product and Parts Manufacturing' },
  { digits_2: 33, digits_4: 3365, title: 'Railroad Rolling Stock Manufacturing' },
  { digits_2: 33, digits_4: 3366, title: 'Ship and Boat Building' },
  { digits_2: 33, digits_4: 3369, title: 'Other Transportation Equipment Manufacturing' },
  { digits_2: 33, digits_4: 3371, title: 'Household and Institutional Furniture and Kitchen Cabinet Manufacturing' },
  { digits_2: 33, digits_4: 3372, title: 'Office Furniture (including Fixtures) Manufacturing' },
  { digits_2: 33, digits_4: 3379, title: 'Other Furniture Related Product Manufacturing' },
  { digits_2: 33, digits_4: 3391, title: 'Medical Equipment and Supplies Manufacturing' },
  { digits_2: 33, digits_4: 3399, title: 'Other Miscellaneous Manufacturing' },
  { digits_2: 42, digits_4: 4231, title: 'Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4232, title: 'Furniture and Home Furnishing Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4233, title: 'Lumber and Other Construction Materials Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4234, title: 'Professional and Commercial Equipment and Supplies Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4235, title: 'Metal and Mineral (except Petroleum) Merchant Wholesalers ' },
  {
    digits_2: 42,
    digits_4: 4236,
    title: 'Household Appliances and Electrical and Electronic Goods Merchant Wholesalers '
  },
  {
    digits_2: 42,
    digits_4: 4237,
    title: 'Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers '
  },
  { digits_2: 42, digits_4: 4238, title: 'Machinery, Equipment, and Supplies Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4239, title: 'Miscellaneous Durable Goods Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4241, title: 'Paper and Paper Product Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4242, title: 'Drugs and Druggists Sundries Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4243, title: 'Apparel, Piece Goods, and Notions Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4244, title: 'Grocery and Related Product Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4245, title: 'Farm Product Raw Material Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4246, title: 'Chemical and Allied Products Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4247, title: 'Petroleum and Petroleum Products Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4248, title: 'Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4249, title: 'Miscellaneous Nondurable Goods Merchant Wholesalers ' },
  { digits_2: 42, digits_4: 4251, title: 'Wholesale Electronic Markets and Agents and Brokers ' },
  { digits_2: 44, digits_4: 4411, title: 'Automobile Dealers ' },
  { digits_2: 44, digits_4: 4412, title: 'Other Motor Vehicle Dealers ' },
  { digits_2: 44, digits_4: 4413, title: 'Automotive Parts, Accessories, and Tire Stores ' },
  { digits_2: 44, digits_4: 4421, title: 'Furniture Stores ' },
  { digits_2: 44, digits_4: 4422, title: 'Home Furnishings Stores ' },
  { digits_2: 44, digits_4: 4431, title: 'Electronics and Appliance Stores ' },
  { digits_2: 44, digits_4: 4441, title: 'Building Material and Supplies Dealers ' },
  { digits_2: 44, digits_4: 4442, title: 'Lawn and Garden Equipment and Supplies Stores ' },
  { digits_2: 44, digits_4: 4451, title: 'Grocery Stores ' },
  { digits_2: 44, digits_4: 4452, title: 'Specialty Food Stores ' },
  { digits_2: 44, digits_4: 4453, title: 'Beer, Wine, and Liquor Stores ' },
  { digits_2: 44, digits_4: 4461, title: 'Health and Personal Care Stores ' },
  { digits_2: 44, digits_4: 4471, title: 'Gasoline Stations ' },
  { digits_2: 44, digits_4: 4481, title: 'Clothing Stores ' },
  { digits_2: 44, digits_4: 4482, title: 'Shoe Stores ' },
  { digits_2: 44, digits_4: 4483, title: 'Jewelry, Luggage, and Leather Goods Stores ' },
  { digits_2: 45, digits_4: 4511, title: 'Sporting Goods, Hobby, and Musical Instrument Stores ' },
  { digits_2: 45, digits_4: 4512, title: 'Book Stores and News Dealers ' },
  { digits_2: 45, digits_4: 4522, title: 'Department Stores ' },
  { digits_2: 45, digits_4: 4523, title: 'General Merchandise Stores, including Warehouse Clubs and Supercenters ' },
  { digits_2: 45, digits_4: 4531, title: 'Florists ' },
  { digits_2: 45, digits_4: 4532, title: 'Office Supplies, Stationery, and Gift Stores ' },
  { digits_2: 45, digits_4: 4533, title: 'Used Merchandise Stores ' },
  { digits_2: 45, digits_4: 4539, title: 'Other Miscellaneous Store Retailers ' },
  { digits_2: 45, digits_4: 4541, title: 'Electronic Shopping and Mail-Order Houses ' },
  { digits_2: 45, digits_4: 4542, title: 'Vending Machine Operators ' },
  { digits_2: 45, digits_4: 4543, title: 'Direct Selling Establishments ' },
  { digits_2: 48, digits_4: 4811, title: 'Scheduled Air Transportation' },
  { digits_2: 48, digits_4: 4812, title: 'Nonscheduled Air Transportation' },
  { digits_2: 48, digits_4: 4821, title: 'Rail Transportation' },
  { digits_2: 48, digits_4: 4831, title: 'Deep Sea, Coastal, and Great Lakes Water Transportation' },
  { digits_2: 48, digits_4: 4832, title: 'Inland Water Transportation' },
  { digits_2: 48, digits_4: 4841, title: 'General Freight Trucking' },
  { digits_2: 48, digits_4: 4842, title: 'Specialized Freight Trucking' },
  { digits_2: 48, digits_4: 4851, title: 'Urban Transit Systems' },
  { digits_2: 48, digits_4: 4852, title: 'Interurban and Rural Bus Transportation' },
  { digits_2: 48, digits_4: 4853, title: 'Taxi and Limousine Service' },
  { digits_2: 48, digits_4: 4854, title: 'School and Employee Bus Transportation' },
  { digits_2: 48, digits_4: 4855, title: 'Charter Bus Industry' },
  { digits_2: 48, digits_4: 4859, title: 'Other Transit and Ground Passenger Transportation' },
  { digits_2: 48, digits_4: 4861, title: 'Pipeline Transportation of Crude Oil' },
  { digits_2: 48, digits_4: 4862, title: 'Pipeline Transportation of Natural Gas' },
  { digits_2: 48, digits_4: 4869, title: 'Other Pipeline Transportation' },
  { digits_2: 48, digits_4: 4871, title: 'Scenic and Sightseeing Transportation, Land' },
  { digits_2: 48, digits_4: 4872, title: 'Scenic and Sightseeing Transportation, Water' },
  { digits_2: 48, digits_4: 4879, title: 'Scenic and Sightseeing Transportation, Other' },
  { digits_2: 48, digits_4: 4881, title: 'Support Activities for Air Transportation' },
  { digits_2: 48, digits_4: 4882, title: 'Support Activities for Rail Transportation' },
  { digits_2: 48, digits_4: 4883, title: 'Support Activities for Water Transportation' },
  { digits_2: 48, digits_4: 4884, title: 'Support Activities for Road Transportation' },
  { digits_2: 48, digits_4: 4885, title: 'Freight Transportation Arrangement' },
  { digits_2: 48, digits_4: 4889, title: 'Other Support Activities for Transportation' },
  { digits_2: 49, digits_4: 4911, title: 'Postal Service' },
  { digits_2: 49, digits_4: 4921, title: 'Couriers and Express Delivery Services' },
  { digits_2: 49, digits_4: 4922, title: 'Local Messengers and Local Delivery' },
  { digits_2: 49, digits_4: 4931, title: 'Warehousing and Storage' },
  { digits_2: 51, digits_4: 5111, title: 'Newspaper, Periodical, Book, and Directory Publishers' },
  { digits_2: 51, digits_4: 5112, title: 'Software Publishers' },
  { digits_2: 51, digits_4: 5121, title: 'Motion Picture and Video Industries' },
  { digits_2: 51, digits_4: 5122, title: 'Sound Recording Industries' },
  { digits_2: 51, digits_4: 5151, title: 'Radio and Television Broadcasting' },
  { digits_2: 51, digits_4: 5152, title: 'Cable and Other Subscription Programming' },
  { digits_2: 51, digits_4: 5173, title: 'Wired and Wireless Telecommunications Carriers' },
  { digits_2: 51, digits_4: 5174, title: 'Satellite Telecommunications' },
  { digits_2: 51, digits_4: 5179, title: 'Other Telecommunications' },
  { digits_2: 51, digits_4: 5182, title: 'Data Processing, Hosting, and Related Services' },
  { digits_2: 51, digits_4: 5191, title: 'Other Information Services' },
  { digits_2: 52, digits_4: 5211, title: 'Monetary Authorities-Central Bank' },
  { digits_2: 52, digits_4: 5221, title: 'Depository Credit Intermediation ' },
  { digits_2: 52, digits_4: 5222, title: 'Nondepository Credit Intermediation ' },
  { digits_2: 52, digits_4: 5223, title: 'Activities Related to Credit Intermediation ' },
  { digits_2: 52, digits_4: 5231, title: 'Securities and Commodity Contracts Intermediation and Brokerage' },
  { digits_2: 52, digits_4: 5232, title: 'Securities and Commodity Exchanges' },
  { digits_2: 52, digits_4: 5239, title: 'Other Financial Investment Activities' },
  { digits_2: 52, digits_4: 5241, title: 'Insurance Carriers' },
  { digits_2: 52, digits_4: 5242, title: 'Agencies, Brokerages, and Other Insurance Related Activities' },
  { digits_2: 52, digits_4: 5251, title: 'Insurance and Employee Benefit Funds ' },
  { digits_2: 52, digits_4: 5259, title: 'Other Investment Pools and Funds' },
  { digits_2: 53, digits_4: 5311, title: 'Lessors of Real Estate' },
  { digits_2: 53, digits_4: 5312, title: 'Offices of Real Estate Agents and Brokers' },
  { digits_2: 53, digits_4: 5313, title: 'Activities Related to Real Estate' },
  { digits_2: 53, digits_4: 5321, title: 'Automotive Equipment Rental and Leasing' },
  { digits_2: 53, digits_4: 5322, title: 'Consumer Goods Rental' },
  { digits_2: 53, digits_4: 5323, title: 'General Rental Centers' },
  { digits_2: 53, digits_4: 5324, title: 'Commercial and Industrial Machinery and Equipment Rental and Leasing' },
  { digits_2: 53, digits_4: 5331, title: 'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)' },
  { digits_2: 54, digits_4: 5411, title: 'Legal Services' },
  { digits_2: 54, digits_4: 5412, title: 'Accounting, Tax Preparation, Bookkeeping, and Payroll Services' },
  { digits_2: 54, digits_4: 5413, title: 'Architectural, Engineering, and Related Services' },
  { digits_2: 54, digits_4: 5414, title: 'Specialized Design Services' },
  { digits_2: 54, digits_4: 5415, title: 'Computer Systems Design and Related Services' },
  { digits_2: 54, digits_4: 5416, title: 'Management, Scientific, and Technical Consulting Services' },
  { digits_2: 54, digits_4: 5417, title: 'Scientific Research and Development Services' },
  { digits_2: 54, digits_4: 5418, title: 'Advertising, Public Relations, and Related Services' },
  { digits_2: 54, digits_4: 5419, title: 'Other Professional, Scientific, and Technical Services' },
  { digits_2: 55, digits_4: 5511, title: 'Management of Companies and Enterprises' },
  { digits_2: 56, digits_4: 5611, title: 'Office Administrative Services' },
  { digits_2: 56, digits_4: 5612, title: 'Facilities Support Services' },
  { digits_2: 56, digits_4: 5613, title: 'Employment Services' },
  { digits_2: 56, digits_4: 5614, title: 'Business Support Services' },
  { digits_2: 56, digits_4: 5615, title: 'Travel Arrangement and Reservation Services' },
  { digits_2: 56, digits_4: 5616, title: 'Investigation and Security Services' },
  { digits_2: 56, digits_4: 5617, title: 'Services to Buildings and Dwellings' },
  { digits_2: 56, digits_4: 5619, title: 'Other Support Services' },
  { digits_2: 56, digits_4: 5621, title: 'Waste Collection ' },
  { digits_2: 56, digits_4: 5622, title: 'Waste Treatment and Disposal ' },
  { digits_2: 56, digits_4: 5629, title: 'Remediation and Other Waste Management Services ' },
  { digits_2: 61, digits_4: 6111, title: 'Elementary and Secondary Schools' },
  { digits_2: 61, digits_4: 6112, title: 'Junior Colleges' },
  { digits_2: 61, digits_4: 6113, title: 'Colleges, Universities, and Professional Schools' },
  { digits_2: 61, digits_4: 6114, title: 'Business Schools and Computer and Management Training' },
  { digits_2: 61, digits_4: 6115, title: 'Technical and Trade Schools ' },
  { digits_2: 61, digits_4: 6116, title: 'Other Schools and Instruction' },
  { digits_2: 61, digits_4: 6117, title: 'Educational Support Services' },
  { digits_2: 62, digits_4: 6211, title: 'Offices of Physicians' },
  { digits_2: 62, digits_4: 6212, title: 'Offices of Dentists' },
  { digits_2: 62, digits_4: 6213, title: 'Offices of Other Health Practitioners' },
  { digits_2: 62, digits_4: 6214, title: 'Outpatient Care Centers' },
  { digits_2: 62, digits_4: 6215, title: 'Medical and Diagnostic Laboratories' },
  { digits_2: 62, digits_4: 6216, title: 'Home Health Care Services' },
  { digits_2: 62, digits_4: 6219, title: 'Other Ambulatory Health Care Services' },
  { digits_2: 62, digits_4: 6221, title: 'General Medical and Surgical Hospitals' },
  { digits_2: 62, digits_4: 6222, title: 'Psychiatric and Substance Abuse Hospitals' },
  { digits_2: 62, digits_4: 6223, title: 'Specialty (except Psychiatric and Substance Abuse) Hospitals' },
  { digits_2: 62, digits_4: 6231, title: 'Nursing Care Facilities (Skilled Nursing Facilities)' },
  {
    digits_2: 62,
    digits_4: 6232,
    title: 'Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities'
  },
  {
    digits_2: 62,
    digits_4: 6233,
    title: 'Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly'
  },
  { digits_2: 62, digits_4: 6239, title: 'Other Residential Care Facilities' },
  { digits_2: 62, digits_4: 6241, title: 'Individual and Family Services' },
  { digits_2: 62, digits_4: 6242, title: 'Community Food and Housing, and Emergency and Other Relief Services' },
  { digits_2: 62, digits_4: 6243, title: 'Vocational Rehabilitation Services' },
  { digits_2: 62, digits_4: 6244, title: 'Child Day Care Services' },
  { digits_2: 71, digits_4: 7111, title: 'Performing Arts Companies' },
  { digits_2: 71, digits_4: 7112, title: 'Spectator Sports' },
  { digits_2: 71, digits_4: 7113, title: 'Promoters of Performing Arts, Sports, and Similar Events' },
  {
    digits_2: 71,
    digits_4: 7114,
    title: 'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures'
  },
  { digits_2: 71, digits_4: 7115, title: 'Independent Artists, Writers, and Performers' },
  { digits_2: 71, digits_4: 7121, title: 'Museums, Historical Sites, and Similar Institutions' },
  { digits_2: 71, digits_4: 7131, title: 'Amusement Parks and Arcades' },
  { digits_2: 71, digits_4: 7132, title: 'Gambling Industries' },
  { digits_2: 71, digits_4: 7139, title: 'Other Amusement and Recreation Industries' },
  { digits_2: 72, digits_4: 7211, title: 'Traveler Accommodation' },
  { digits_2: 72, digits_4: 7212, title: 'RV (Recreational Vehicle) Parks and Recreational Camps' },
  { digits_2: 72, digits_4: 7213, title: 'Rooming and Boarding Houses, Dormitories, and Workers Camps' },
  { digits_2: 72, digits_4: 7223, title: 'Special Food Services' },
  { digits_2: 72, digits_4: 7224, title: 'Drinking Places (Alcoholic Beverages)' },
  { digits_2: 72, digits_4: 7225, title: 'Restaurants and Other Eating Places' },
  { digits_2: 81, digits_4: 8111, title: 'Automotive Repair and Maintenance' },
  { digits_2: 81, digits_4: 8112, title: 'Electronic and Precision Equipment Repair and Maintenance' },
  {
    digits_2: 81,
    digits_4: 8113,
    title: 'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance'
  },
  { digits_2: 81, digits_4: 8114, title: 'Personal and Household Goods Repair and Maintenance' },
  { digits_2: 81, digits_4: 8121, title: 'Personal Care Services ' },
  { digits_2: 81, digits_4: 8122, title: 'Death Care Services ' },
  { digits_2: 81, digits_4: 8123, title: 'Drycleaning and Laundry Services ' },
  { digits_2: 81, digits_4: 8129, title: 'Other Personal Services ' },
  { digits_2: 81, digits_4: 8131, title: 'Religious Organizations ' },
  { digits_2: 81, digits_4: 8132, title: 'Grantmaking and Giving Services ' },
  { digits_2: 81, digits_4: 8133, title: 'Social Advocacy Organizations ' },
  { digits_2: 81, digits_4: 8134, title: 'Civic and Social Organizations ' },
  { digits_2: 81, digits_4: 8139, title: 'Business, Professional, Labor, Political, and Similar Organizations ' },
  { digits_2: 81, digits_4: 8141, title: 'Private Households' },
  { digits_2: 92, digits_4: 9211, title: 'Executive, Legislative, and Other General Government Support ' },
  { digits_2: 92, digits_4: 9221, title: 'Justice, Public Order, and Safety Activities ' },
  { digits_2: 92, digits_4: 9231, title: 'Administration of Human Resource Programs ' },
  { digits_2: 92, digits_4: 9241, title: 'Administration of Environmental Quality Programs ' },
  {
    digits_2: 92,
    digits_4: 9251,
    title: 'Administration of Housing Programs, Urban Planning, and Community Development '
  },
  { digits_2: 92, digits_4: 9261, title: 'Administration of Economic Programs ' },
  { digits_2: 92, digits_4: 9271, title: 'Space Research and Technology ' },
  { digits_2: 92, digits_4: 9281, title: 'National Security and International Affairs ' }
];
